### PR TITLE
trackStart prop for Slider component

### PR DESCRIPTION
**Pull request by iqqmuT**
By default the track starts from `min` value in Slider component. With new `trackStart` prop you can define where the track starts from.

Examples:
horizontal
vertical

See #488

### CODE REVIEW

**Comment by zombieJ** [comment]
What's the best name of this prop? I have some concern.
Is that `centre` or `startPoint` or `basePoint` better?

@amoebageek  @iqqmuT  @afc163

**Comment by iqqmuT** [comment]
It's surprisingly hard to come up with the right prop name. `startPoint` sounds good.

**Comment by amoebageek** [comment]
> It's surprisingly hard to come up with the right prop name. `startPoint` sounds good.

Yes I agree, saying it startPoint is good

**Comment by zombieJ** [comment]
@iqqmuT , could you help to update?

**Comment by zombieJ** [comment]
`+ rc-slider@9.1.0`

**Pull request merged**
