### PR TITLE
fix(#19879): focusing the wrong handle when using range

### PR DESCRIPTION
**Pull request by Kermit-Xuan**
[#19879](https://github.com/ant-design/ant-design/issues/19879)

### CODE REVIEW

**Comment by Kermit-Xuan** [comment]
@afc163

**Comment by Kermit-Xuan** [comment]
@afc163

**Comment by zombieJ** [comment]
Could you help to add a test case for this patch?

**Comment by Kermit-Xuan** [comment]
I don't see the test case about `allowCross` is `true` or drag.

**Comment by Kermit-Xuan** [comment]
I have add test case for it

**Pull request merged**
