### PR TITLE
put marks in correct order so one can style it

### PR DESCRIPTION
**Pull request by kalinichenko**
I need to change styles of the first and last marks. I couldn't find any other way but to put them in correct order.

### CODE REVIEW

**Comment by just-boris** [comment]
Hello. Why can't you sort marks before passing it down to the component?

Also I have a use case with string values in marks: 

image

Your pull request probably will break this use-case.

**Comment by kalinichenko** [comment]
@just-boris I am not sure I got you right. Slider expects to get an object for marks. Marks component use keys from marks object to create elements. How can I specify an order for them?

**Comment by just-boris** [comment]
Well, I got it. Now you have the following collection:

```js
var marks = {
   2: 'c',
   0: 'a',
   1: 'b'
}
```
And you want to preserve the order of keys. That makes sense.

LGTM.

**Comment by benjycui** [comment]
THX!

**Pull request merged**
