### PR TITLE
Allow callback for "dotStyle" and "activeDotStyle" props - with tests

### PR DESCRIPTION
**Pull request by yann-combarnous**
Same as PR #828, but with added tests.
- [x] updated README
- [x] updated typescript typedefs
- [x] added callback option for the  "dotStyle" and "activeDotStyle" props
- [x] added tests 

close #828

### CODE REVIEW

**Comment by yann-combarnous** [comment]
@yoyo837 , I re-opened this PR, with tests added, even though I cannot run them on my system.

**Comment by yann-combarnous** [comment]
@yoyo837 , fixed the actual/expected values, please allow the tests to run. Thx.

**Comment by yoyo837** [comment]
CI failed.

**Comment by yann-combarnous** [comment]
> CI failed.

Yep, but first test passed (container1), so now I fixed offset for second test (container2). Sorry for the iterations, a bit difficult to get right without being able to run the tests locally.

**Pull request merged**
