### PR TITLE
Allow to pass custom handle components

### LINKED ISSUE #63: feature: customizable handle
Lots of issues are about making tooltip more configurable.

1. #62 wants to show tooltip anytime.
1. #32 wants to format tooltip's content, and disabled tooltip.

rc-slider has become a fattie. And it seems that all of rc-tooltip's APIs are going to be exposed.

How about @just-boris ' suggestion? https://github.com/react-component/slider/issues/32#issuecomment-156748583

If rc-slider supported customizable handle, you could wrap handle with any kind of tooltip. But the drawback is that it is not as convenient as `tipFormatter` or `tipVisibility`.

### PR DESCRIPTION
**Pull request by just-boris**
First attempt to resolve #63.

I like that because it doesn't cause a lot of changes in the source code. It just works. Then we need to document it and describe the properties which are passed to handle component.

I tried to make few examples how it can be used. This is how it looks like.
image

### CODE REVIEW

**Comment by yiminghe** [comment]
just pass a handle element is more customizable .

```js
<Slide handle={<MyHandle xx="yy"/>}>
```

**Comment by just-boris** [comment]
@yiminghe it will not work. You can't get handle position in that way.

If you want to pass extra props to custom handle, you can do this

```
<Slide handle={({offset, value}) => <MyHandle xx="yy" offset={offset}>}>
```

And technically it would be a short form of this:

```
function HandleWrapper({offset, value}) {
   return <MyHandle xx="yy" offset={offset}>;
}
<Slide handle={HandleWrapper}>
```

**Comment by yiminghe** [comment]
inside rc-slider:
```
React.cloneElement(handle, {
 ...
});
```

see usage of rc-calendar: http://react-component.github.io/calendar/examples/antd-calendar.html

**Comment by just-boris** [comment]
As it seems to me, it is a bit unclear for developer how it works.

But since you already have success story in the calendar, so it should be done here in the same way. I will update my PR by the end of week.

**Comment by benjycui** [comment]
Close for no update. 

Just reopen or create a new PR when you have time to complete it. @just-boris

**Comment by just-boris** [comment]
Sorry, I messed up and forgot about this. Of course, I will make all necessary fixes and create new when I got the time.

**Pull request closed without merging**
