### PR TITLE
[WIP] Range keyboard implementation

### PR DESCRIPTION
**Pull request by byCedric**
As announced in PR #298 and build for PR #131 (accessibility) here is the implementation for the Range components. I kept this from the other PR to make sure everything was correctly implemented for the Slider first.

> This is a Work In Progress, right now it lacks tests.

### CODE REVIEW

**Comment by deadline98** [comment]
@byCedric Any news on this? Would be really helpfull to get this functionallity. I was currently working on the handling myself but ended up finding this PullRequest.

**Comment by byCedric** [comment]
@deadline98 Well, when I tried to implement this for the range I came across another issue (#298). I see that a potential fix was closed on 8th of August. Let me update this PR tonight and I will check if the issue has been resolved already.

**Comment by byCedric** [comment]
@Shardendu-kantha The implementation of keyboard support for range sliders is still blocked by issue #298. If I push this support without the fix for the faulty element focus the UX will be horrible. If you have time maybe you can help try solving this issue...

**Comment by yesmeck** [comment]
Closing in favor of #396

**Pull request closed without merging**
