### PR TITLE
Add support for 'alwaysVisible' property

### PR DESCRIPTION
**Pull request by uberstudio**
This adds support for when we want the tooltip to be always visible

### CODE REVIEW

**Comment by glorp47** [comment]
+1 for having this type of functionality ...

**Comment by paranoidjk** [comment]
Thanks for your PR. But you can do this by custom handle, eg: https://github.com/react-component/slider/blob/master/examples/handle.js#L34

**Comment by hellofantastic** [comment]
The docs or readme says Range component supports handle but id I have <Range  handle={(props=>{this.tooltipHandle(props) }}  nothing fires... but if I add it to Slider it does work... insight? 

```javascript
...
tooltipHandle = (props) => {
        const { value, dragging, index, ...restProps } = props;
        console.log('tooltip');
        return (
          <Tooltip
            prefixCls="rc-slider-tooltip"
            overlay={value}
            visible={true}
            defaultVisible={true}
            placement="bottom"
            key={index}
          >
            <Handle value={value} {...restProps} />
          </Tooltip>
        );
    };
...
<Range
                                className="mt-3"
                                style={this.props.rangeStyle}
                                min={0}
                                max={100}
                                value={this.state.rangeValues[rangeConfig.field]}
                                
                                handle={(props)=>{ console.log(props); }}
                                onChange={(value) => { this.onRangeChange(rangeConfig.field, value); }}
                                onAfterChange={(value) => {this.onAfterRangeChange(rangeConfig.field, value);}}
                            />
                            <Slider  min={0}
                                max={100}
                                handle={(props)=>{ console.log(props); }}/>
```

**Comment by uberstudio** [comment]
Just do
```handle={tooltipHandle}```

Looks like you're just logging there instead of using the handle function you wrote :)

**Pull request closed without merging**
