### PR TITLE
Add handleStyle and minimumTrackStyle props to Range

### PR DESCRIPTION
**Pull request by gragland**
Previously the `handleStyle` and `minimumTrackStyle` props only worked with Slider. Added them to Range as well.

### CODE REVIEW

**Comment by paranoidjk** [comment]
since Range has multiple track and handle，so the api name may be confused, we need to think about it.

https://github.com/react-component/slider/pull/249

**Comment by gragland** [comment]
Maybe innerTrackStyle and outerTrackStyle would be more appropriate names. It makes sense for Range, and for the slider I don't think it's too much of a stretch to consider the track to the left of the handle to be "inner".. What do you think?

**Comment by paranoidjk** [comment]
@benjycui

**Comment by gragland** [comment]
Opened a new pull request for this since this one was pointing to my master branch. Sorry for the confusion. See: https://github.com/react-component/slider/pull/255

**Pull request closed without merging**
