### PR TITLE
fixed `onChange` which fired on every mousmove, added test

### PR DESCRIPTION
**Pull request by Fuzzyma**
This PR fixes react-component/slider/issues/144

I tried to lint but linting fails because of modules not installed and wrong config values.
Also tried using `ReactTestUtils.Simulate` for tests without success.
At least I tried...

### CODE REVIEW

**Comment by benjycui** [comment]
Thanks!

But, could you resolve CI failed?

**Comment by Fuzzyma** [comment]
At the time writing this PR your test suite failed because of an internal error and not because of the actual test failing. Is that fixed?

**Comment by benjycui** [comment]
Sorry, my bad..

**Comment by benjycui** [comment]
Done, please rebase, thanks!

**Pull request merged**
