### PR TITLE
Fix #279 - Use getBoundingClientRect for proper scaled width of slider

### LINKED ISSUE #279: Wrong handle position when scaled
The slider handle is not placed at the right position when it is scaled.

Step to reproduce : Place the slider inside a scaled div

const wrapperStyle = { width: 400, margin: 50,transform:scale(0.5) };
ReactDOM.render(
  <div>
    <div style={wrapperStyle}>
      <p>Slider with custom handle</p>
      <Slider min={0} max={20} defaultValue={3} handle={handle} />
    </div>
    <div style={wrapperStyle}>
      <p>Range with custom handle</p>
      <Range min={0} max={20} defaultValue={[3, 10]} tipFormatter={value => `${value}%`} />
    </div>
  </div>,
  document.getElementById('__react-content')
);

I changed line 211 in lib/common/CreateSlider.js and it works for me :

Prev :  return this.props.vertical ? slider.clientHeight : slider.clientWidth;
Now :  return this.props.vertical ? slider.getBoundingClientRect().height : slider.getBoundingClientRect().width;

### PR DESCRIPTION
**Pull request by dbryand**
Jcqt-390's solution also worked for me:
https://github.com/react-component/slider/issues/279

### CODE REVIEW

**Comment by dbryand** [comment]
I see now that this gives failing tests. Will take a look.

**Comment by captbaritone** [comment]
I've cherry-picked your commit into a separate pull request which also resolves the failing tests.

**Comment by benjycui** [comment]
@dbryand could you fix the CI and add a unit test for this?

**Comment by benjycui** [comment]
> add a unit test for this?

Oops.. it seems that it is hard to add unit test for this. But please fix CI at least.

**Comment by dbryand** [comment]
Will give it a shot when back to work in a few days.

**Comment by paranoidjk** [comment]
@dbryand 👍 
Thx, your commit have been merged in https://github.com/react-component/slider/pull/293

**Pull request closed without merging**
