### PR TITLE
tooltipAlwaysVisible prop added

### PR DESCRIPTION
**Pull request by kazkovsky**
Setting tooltipAlwaysVisible on true makes tooltip always visible. Useful for specific designs.

### CODE REVIEW

**Comment by ykka** [comment]
:+1:

**Comment by benjycui** [comment]
This implementation is a little verbose. Sorry to close now. And I will provide a solution to controll the visibility of tooltip in next version.

**Comment by lauterry** [comment]
Hello @benjycui 

Have you been able to provide a solution to control the visibility of tooltip in next version ?

Is it still in the pipe ?

Best regards

**Comment by benjycui** [comment]
Try http://react-component.github.io/slider/examples/custom-handles.html

**Comment by hellofantastic** [comment]
404, does it exist somewhere else.
I am attempting tip always visible no matter what , found the rc-tooltip example but not working... of course I should put up some of what I already  tried after I attempt another ...attempt.

**Pull request closed without merging**
