### PR TITLE
Migrated deprecated React.PropTypes and React.createClass

### PR DESCRIPTION
**Pull request by Andarist**

### CODE REVIEW

**Comment by paranoidjk** [comment]
Add related info: https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

**Comment by paranoidjk** [comment]
👍  Thanks

**Comment by benjycui** [comment]
@Andarist how about refactoring this to ES6 class?

**Comment by Andarist** [comment]
@benjycui 
yeah, that's something I was thinking about too, but had not that much time for updates, I've kinda went for a run and helped few libraries with the migration at once, so Ive wanted to keep changes to the minimum

That is certainly something that should be prepared before `v16`, so by then it's already ready. You can create an issue about the matter and mention me there - if I find time Im gonna do it, but no hard promises though.

**Pull request merged**
