### PR TITLE
Startpoint from mark

### PR DESCRIPTION
**Pull request by amoebageek**
slider: Start the handler from the marked starting point within the min-max of the track. This is to support the custom start point in the rail and track will forward and backward of the marked point.
Profile-20200109T001948

### CODE REVIEW

**Comment by amoebageek** [comment]
@afc163 @uwolfer  please review

**Comment by zombieJ** [comment]
Hi, what's the different with set `value`? Not get start point meaning yet...

**Comment by iqqmuT** [comment]
Duplicate PR: #609

**Comment by zombieJ** [comment]
Got it. It's about show the range between start point. Right

**Comment by zombieJ** [comment]
hi @amoebageek, is @iqqmuT PR cover your requirement?

**Comment by amoebageek** [comment]
> hi @amoebageek, is @iqqmuT PR cover your requirement?

Yes, it seems PR #609 is covering the requirement, by when we can expect to merge?

**Comment by zombieJ** [comment]
Let's move into #609

**Comment by anujayk** [comment]
@zombieJ @iqqmuT  i guess types are not merged for startPoint props

**Pull request closed without merging**
