### PR TITLE
Fixed issue where controlled Range sliders with allowCross=false and …

### PR DESCRIPTION
**Pull request by Oddsor**
…more than two handles would change values of handles that aren't currently being dragged

This fully(?) solves issue https://github.com/react-component/slider/issues/226

### CODE REVIEW

**Comment by Oddsor** [comment]
Added a test case that describes the original issue I encountered with issue #226, along with a proposed fix.

This is basically my first open source contribution, so any feedback would be appreciated!

**Comment by Robin-front** [comment]
similar to #304 , cause wrong handle, didn't pass `index` when `map`

**Comment by Oddsor** [comment]
Very similar indeed! It looks like your pull request is missing a test case for this particular issue however. Maybe I could limit the pull request to this.

**Comment by yesmeck** [comment]
#304 has been merged, try 8.6.1

**Pull request closed without merging**
