### PR TITLE
Allow custom track and step renderers.

### PR DESCRIPTION
**Pull request by alampros**
Add `trackComponent` prop.
Add `stepsComponent` prop.
Add tests and updated docs.

### CODE REVIEW

**Comment by just-boris** [comment]
Hello! Thank you for you contribution!

But track and step are just a single html-element. Why do you need to customize them? I think, that the most customizing issues can be solved with just CSS.

**Comment by alampros** [comment]
@just-boris No problem, thanks for the quick response!

I'd like to provide a custom track component that draws a histogram of all available values using a `<canvas>` element. This would give the user some idea of what kind of change their actions might produce. I'll post a screenshot of my mockup when it's done.

Feel free to close this PR if this is too much of an edge case.

**Comment by just-boris** [comment]
Well, I saw similar example in [angular-slider](http://angular-slider.github.io/angularjs-slider/) projejct (see "Slider with dynamic selection bar color" demo). Maybe it makes sense.

The final decision is on @benjycui

**Comment by alampros** [comment]
Hold off on merging this – I think I botched the implementation. I'll rethink it and reopen it if needed. Sorry!

**Comment by just-boris** [comment]
Well, just use [custom handle implementation](https://github.com/react-component/slider/blob/master/src/Slider.jsx#L342) as example.

**Comment by alampros** [comment]
I think I got it. Sorry, I should be allowed to push commits without sufficient coffee.

**Comment by benjycui** [comment]
> Feel free to close this PR if this is too much of an edge case.

Yes, it is not common use case.

> I'll post a screenshot of my mockup when it's done.

This PR will be close, but I still hope that you could post your screenshot. If someone need similar feature, maybe he/she can use your fork version.

Thanks :-)

**Pull request closed without merging**
