### PR TITLE
Added dotStyle and activeDotStyle

### PR DESCRIPTION
**Pull request by tomoberry**
I was thinking something like this for adding styling to the dots

### CODE REVIEW

**Comment by benjycui** [comment]
😒

**Comment by paranoidjk** [comment]
@tomoberry 

Thanks for you pr. 
But since we have `rc-slider-dot`, `rc-slider-dot-active` classname, why not custom style with css?

**Comment by tomoberry** [comment]
I have a use case where I need to support an arbitrary number of different color combinations for the slider.  A simple example would be making an ajax call to a server that returns a random color that the slider should be displayed in.

**Comment by paranoidjk** [comment]
hmm, i got this reature request from another user too.

So i am going to merge this and release a minor upgrade.

**Comment by paranoidjk** [comment]
`rc-slider@8.2.0`

**Pull request merged**
