### PR TITLE
add reverse props that values will increase from top to bottom or right to left

### PR DESCRIPTION
**Pull request by DMIAOCHEN**
#178

### CODE REVIEW

**Comment by afc163** [comment]
How about just `reverse`?

**Comment by DMIAOCHEN** [comment]
`verticalReverse` just a props name， if you want, you can call any others, this pr's main function is provide a method that the slider can increase from top to bottom when  vertical, any suggest?

**Comment by afc163** [comment]
`reverse` includes `verticalReverse` and `horizontalReverse`, is more common.

**Comment by DMIAOCHEN** [comment]
er.. of course!
how about name this prop `revers`, then add `horizontalReverse` features?

**Comment by benjycui** [comment]
A little complicated to implement such a simple feature...

Just use `tipFormatter` and map value in `onChange` now..

**Comment by DMIAOCHEN** [comment]
can you give a demo, please.

**Pull request closed without merging**
